version: '3'
services:
  front:
    build:
      context: ./frontend
    image: front
    container_name: front
    ports:
      - "80:80"

  back:
    build:
      context: ./backend
    image: back
    container_name: back
    ports:
      - "8080:8080"
    environment:
      TZ: "Asia/Seoul"
      server.address: 0.0.0.0