VAGRANT_API_VERSION ="2"

vms = {
  'eth0' => '10',
  'eth1' => '11'
}

Vagrant.configure(VAGRANT_API_VERSION) do |config|
  config.vm.box = "ubuntu/bionic64"
  vms.each do |key, value|
    config.vm.define "#{key}" do |node|
      node.vm.network "private_network", ip: "192.168.50.#{value}"
      if "#{key}" == "eth0"
        node.vm.network "forwarded_port", guest: 8545, host: 8545
        config.vm.synced_folder "host폴더", "/home/vagrant/공유폴더이름"
      end
      node.vm.hostname = "#{key}"
      node.vm.provider "virtualbox" do |nodev|
        nodev.memory = 2048
      end
    end
  end
end
